// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie_Collection.Models;

#nullable disable

namespace Movie_Collection.Migrations
{
    [DbContext(typeof(EnterMoviesContext))]
    [Migration("20240217004458_final")]
    partial class final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Movie_Collection.Models.Film", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilmCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmDirector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FilmEdited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilmLentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmNotes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilmTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FilmYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmID");

                    b.ToTable("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
